### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by Gabe-Karras** [Gabe-Karras/module-23#1]
**User Story:**
As a mini canvas user, I would like for there to be tests in all of the methods behind the scenes so the amount of bugs I will encounter is minimized.

**Description:**
Add unit tests to all of the methods and use fixture and mocker

**Task List:**
- [x] Install required testing libraries
- [x] Write unit tests for all methods in project
- [x] Use mocker to effectively test results
- [x] Use fixture to arrange more effectively

**Acceptance criteria:**
* Tests have satisfactory coverage
* Each method has at least one unit test

**Acceptance testing**
* Testing tests correctly!
